### ISSUE TITLE
Template Changes - HOME PAGE

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#133]
Sebastian has provided us with specs for the template changes:

HOME PAGE
![1a-almreports-search-spec](https://cloud.githubusercontent.com/assets/3666130/5593853/5cca5586-91df-11e4-9748-f810f9b35598.png)

As the screen shot shows, we need to re-insert the white space around the grey body area.  This provides a border on the left, right, and bottom.  The grey body area starts where edge of the Select Article tab begins on the left and runs through the right View Report tab.  

Once you get into the grey area, please insert the 40 px margins on both sides as the mockup has specifies. Please ensure that these margins persist throughout the entire site.

**Comment by jure** [comment]
Quite tricky. The styling of dropdowns that's currently in production has been removed before, because it's tricky and carries a lot of baggage/bloat in terms of markup and CSS. Given that PLOS doesn't seem to style dropdowns in this manner on other pages (that I could find), perhaps it is OK to use vanilla styling (shown below)?

Does this look better? Fixed buttons, fixed margins, fixed fonts.

![image](https://cloud.githubusercontent.com/assets/238667/5596043/13084fca-9284-11e4-8d87-15ff2957752a.png)

**Comment by jure** [comment]
TODO: Decrease bottom margin after "BY DOI/PMID"

**Comment by jure** [comment]
Fixed the TODO above. It's not possible (without significant effort) to get the exact column widths and intramargins (30px), due to the way the framework works, but they're as close as possible. The outer margin is 40px as designed.

![image](https://cloud.githubusercontent.com/assets/238667/5611426/c5a9e8f2-94c6-11e4-9677-0fbe5e2d2799.png)
